import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import styles from "./mainLayout.module.scss";
import HeaderWidget from "@/widgets/Header/HeaderWidget";
import FooterWidget from "@/widgets/Footer/FooterWidget";
import Container from "@/shared/ui/Container/Container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: '%s - Nikitas next app',
    default: '',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.layout}`}>
        <HeaderWidget />
          <main className={styles.main}>
              <Container>
                {children}
              </Container>
          </main>
        <FooterWidget />
      </body>
      </html>
  );
}
